source "https://rubygems.org"
ruby '2.5.1'
gem 'rspec'
gem 'pry'
gem 'rubocop', '~> 0.57.2'
gem 'nokogiri'
gem 'watir'
gem 'dotenv'
gem 'selenium-webdriver'
gem 'google_drive'
gem 'json'
gem 'csv'
gem 'gemoji'
gem 'colorize'
gem 'tty-prompt'
gem 'mime'
gem 'mail'
gem 'sinatra'